name: promote
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Wifi-hotspot-config version to promote'
        required: true
        default: latest

jobs:
  snaps:
    uses: canonical/robotics-actions-workflows/.github/workflows/promote.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      snap: wifi-hotspot-config
      from-channel: '${{ inputs.version }}/candidate'
      to-channel: '${{ inputs.version }}/stable'
