name: Monthly builds

on:
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@main
    secrets:
      snapstore-login: ${{ secrets.STORE_LOGIN }}
    with:
      runs-on: '["ubuntu-latest", ["self-hosted", "linux", "ARM64", "medium", "noble"]]'
      git-ref: ${{ inputs.branch-name == '' && github.ref || inputs.branch-name }}
      snapcraft-channel: '8.x/stable'
